[Features]
; 1 = Bật, 0 = Tắt
EnableLogging=1
EnableCapture=1
EnableDebug=0

[Radar]
; Toạ độ nút Give Up (để click mù sau khi spam E)
GiveUpX=960
GiveUpY=202

; Thông số màu Pixel (Dùng Window Spy để lấy mã Hex của chữ Xanh lá "It's right in front of me")
TargetColor=0x81EF6F

; Độ sai lệch màu cho phép (0 - 255)
ColorVariation=30

; Vùng quét Radar (Để giảm tải và tránh nhận diện nhầm UI khác)
ScanX=948
ScanY=155
ScanW=20
ScanH=10

